"""
Convert lerobot v3.0 dataset (generated by lerobot 0.4.4) to openpi-compatible v2.1 format.

v3.0 format (lerobot 0.4.4):
  - data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet  (multiple episodes per file)
  - images stored as {'bytes': b'...', 'path': None} dicts
  - meta/tasks.parquet
  - meta/episodes/chunk-000/file-000.parquet

v2.1 format (openpi lerobot 0.1.0):
  - data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet  (one file per episode)
  - images stored with HuggingFace 'huggingface' parquet metadata marking them as Image type,
    so that load_dataset("parquet", ...) auto-decodes bytes → PIL images
  - meta/tasks.jsonl
  - meta/episodes.jsonl
  - meta/episodes_stats.jsonl  (required by lerobot 0.1.0 v2.1)
  - meta/stats.json
  - meta/info.json   (codebase_version: v2.1, correct data_path template)

Run with openpi uv env (datasets==3.6.0):
  cd ~/VLA_workspace/maniskill_myws/third_party/openpi
  uv run python ../../scripts/convert_v3_to_openpi_compat.py
"""

import io
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image as PILImage

import datasets as hf_datasets

# ── paths ──────────────────────────────────────────────────────────────────────
SRC_ROOT = Path("/home/yozakur4/VLA_workspace/maniskill_myws/datasets/local/open_safe_door2")
DST_ROOT = Path("/home/yozakur4/VLA_workspace/maniskill_myws/datasets/open_safe_door2")

CHUNKS_SIZE = 1000  # episodes per chunk (same as lerobot default)
IMAGE_KEYS  = ["image", "wrist_image"]

# ── HuggingFace dataset features (matches info.json features) ─────────────────
# This Feature spec causes datasets to embed 'huggingface' metadata in the parquet,
# which makes load_dataset auto-decode the image struct → PIL Image.
HF_FEATURES = hf_datasets.Features({
    "image":         hf_datasets.Image(),
    "wrist_image":   hf_datasets.Image(),
    "state":         hf_datasets.Sequence(hf_datasets.Value("float32"), length=7),
    "actions":       hf_datasets.Sequence(hf_datasets.Value("float32"), length=7),
    "timestamp":     hf_datasets.Value("float32"),
    "frame_index":   hf_datasets.Value("int64"),
    "episode_index": hf_datasets.Value("int64"),
    "index":         hf_datasets.Value("int64"),
    "task_index":    hf_datasets.Value("int64"),
})

# ── helpers ────────────────────────────────────────────────────────────────────

def to_pil(raw) -> PILImage.Image:
    """Normalize any image representation → PIL Image (RGB)."""
    if isinstance(raw, dict):
        raw = raw["bytes"]
    if isinstance(raw, (bytes, bytearray)):
        return PILImage.open(io.BytesIO(raw)).convert("RGB")
    if isinstance(raw, PILImage.Image):
        return raw.convert("RGB")
    raise TypeError(f"Unexpected image type: {type(raw)}")


def ep_df_to_hf_dataset(df_ep: pd.DataFrame) -> hf_datasets.Dataset:
    """
    Convert one episode's DataFrame → HuggingFace Dataset with Image features.
    PIL images are stored in the dataset; datasets.to_parquet() writes the
    'huggingface' metadata that enables load_dataset to decode them automatically.
    """
    data_dict = {}
    for col in df_ep.columns:
        if col in IMAGE_KEYS:
            data_dict[col] = [to_pil(v) for v in df_ep[col]]
        else:
            vals = df_ep[col].tolist()
            cleaned = []
            for v in vals:
                if isinstance(v, np.ndarray):
                    cleaned.append(v.tolist())
                elif isinstance(v, np.generic):
                    cleaned.append(v.item())
                else:
                    cleaned.append(v)
            data_dict[col] = cleaned

    return hf_datasets.Dataset.from_dict(data_dict, features=HF_FEATURES)


def _to_serializable(v):
    """Recursively convert numpy types to plain Python for JSON serialization."""
    if isinstance(v, np.ndarray):
        return _to_serializable(v.tolist())  # handles object arrays recursively
    if isinstance(v, np.generic):
        return v.item()
    if isinstance(v, (list, tuple)):
        return [_to_serializable(x) for x in v]
    if isinstance(v, dict):
        return {k: _to_serializable(vv) for k, vv in v.items()}
    return v


# ── main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"Source: {SRC_ROOT}")
    print(f"Dest:   {DST_ROOT}")

    # ── 0. Wipe and recreate destination ──────────────────────────────────────
    if DST_ROOT.exists():
        if DST_ROOT.is_symlink():
            DST_ROOT.unlink()
            print("Removed symlink at destination.")
        else:
            shutil.rmtree(DST_ROOT)
            print("Removed existing destination directory.")
    DST_ROOT.mkdir(parents=True, exist_ok=True)

    # ── 1. Read source info.json ───────────────────────────────────────────────
    with open(SRC_ROOT / "meta" / "info.json") as f:
        src_info = json.load(f)

    total_episodes = src_info["total_episodes"]
    total_frames   = src_info["total_frames"]
    fps            = src_info["fps"]
    robot_type     = src_info["robot_type"]
    features       = src_info["features"]

    print(f"Total episodes: {total_episodes}, total frames: {total_frames}, fps: {fps}")

    # ── 2. Read all source parquet files ──────────────────────────────────────
    print("Reading source parquet files ...")
    src_data_dir = SRC_ROOT / "data"
    all_dfs = []
    for chunk_dir in sorted(src_data_dir.iterdir()):
        for pq_file in sorted(chunk_dir.glob("file-*.parquet")):
            df = pd.read_parquet(pq_file)
            all_dfs.append(df)
            print(f"  Loaded {pq_file.name} ({len(df)} rows)")
    full_df = pd.concat(all_dfs, ignore_index=True)
    print(f"Total rows loaded: {len(full_df)}")
    assert len(full_df) == total_frames, \
        f"Frame count mismatch: loaded {len(full_df)} vs expected {total_frames}"

    # ── 3. Read episode metadata ───────────────────────────────────────────────
    print("Reading episode metadata ...")
    ep_meta_file = SRC_ROOT / "meta" / "episodes" / "chunk-000" / "file-000.parquet"
    ep_meta_df = pd.read_parquet(ep_meta_file)
    ep_lengths = {int(row["episode_index"]): int(row["length"])
                  for _, row in ep_meta_df.iterrows()}

    # Extract per-episode stats (v3.0: columns named stats/{key}/{stat})
    stats_cols = [c for c in ep_meta_df.columns if c.startswith("stats/")]
    per_ep_stats = {}
    for _, row in ep_meta_df.iterrows():
        ep_idx = int(row["episode_index"])
        ep_stats = {}
        for col in stats_cols:
            parts = col.split("/")
            key, stat = parts[1], parts[2]
            if key not in ep_stats:
                ep_stats[key] = {}
            ep_stats[key][stat] = row[col]
        per_ep_stats[ep_idx] = ep_stats

    # ── 4. Read tasks ──────────────────────────────────────────────────────────
    tasks_pq = pd.read_parquet(SRC_ROOT / "meta" / "tasks.parquet")
    task_map = {}
    for task_str, row in tasks_pq.iterrows():
        task_map[int(row["task_index"])] = str(task_str)
    print(f"Tasks: {task_map}")

    # ── 5. Write per-episode parquet files ────────────────────────────────────
    print("Writing per-episode parquet files ...")
    (DST_ROOT / "data").mkdir(parents=True, exist_ok=True)

    episodes_jsonl_rows = []

    for ep_idx in range(total_episodes):
        ep_chunk = ep_idx // CHUNKS_SIZE
        ep_dir = DST_ROOT / "data" / f"chunk-{ep_chunk:03d}"
        ep_dir.mkdir(parents=True, exist_ok=True)
        ep_file = ep_dir / f"episode_{ep_idx:06d}.parquet"

        # Extract this episode's rows
        mask = full_df["episode_index"] == ep_idx
        df_ep = full_df[mask].reset_index(drop=True)

        expected_len = ep_lengths.get(ep_idx)
        assert len(df_ep) == expected_len, \
            f"Episode {ep_idx}: expected {expected_len} frames, got {len(df_ep)}"

        # Convert to HF Dataset with Image() features and save as parquet.
        # datasets.to_parquet() embeds 'huggingface' metadata so that
        # load_dataset("parquet", ...) knows to decode image bytes → PIL.
        hf_ds = ep_df_to_hf_dataset(df_ep)
        hf_ds.to_parquet(str(ep_file))

        # Collect episodes.jsonl entry
        task_indices = df_ep["task_index"].unique().tolist()
        tasks_for_ep = [task_map[int(ti)] for ti in task_indices]
        episodes_jsonl_rows.append({
            "episode_index": ep_idx,
            "tasks": tasks_for_ep,
            "length": int(len(df_ep)),
        })

        if ep_idx % 10 == 0 or ep_idx == total_episodes - 1:
            print(f"  Episode {ep_idx:3d}/{total_episodes - 1}  ({len(df_ep)} frames) → {ep_file.name}")

    # ── 6. Write meta/tasks.jsonl ─────────────────────────────────────────────
    (DST_ROOT / "meta").mkdir(parents=True, exist_ok=True)
    tasks_jsonl_path = DST_ROOT / "meta" / "tasks.jsonl"
    with open(tasks_jsonl_path, "w") as f:
        for task_idx, task_str in sorted(task_map.items()):
            f.write(json.dumps({"task_index": task_idx, "task": task_str}) + "\n")
    print(f"Wrote {tasks_jsonl_path}")

    # ── 7. Write meta/episodes.jsonl ──────────────────────────────────────────
    episodes_jsonl_path = DST_ROOT / "meta" / "episodes.jsonl"
    with open(episodes_jsonl_path, "w") as f:
        for row in episodes_jsonl_rows:
            f.write(json.dumps(row) + "\n")
    print(f"Wrote {episodes_jsonl_path}")

    # ── 8. Write meta/episodes_stats.jsonl (required by lerobot 0.1.0 v2.1) ───
    episodes_stats_path = DST_ROOT / "meta" / "episodes_stats.jsonl"
    with open(episodes_stats_path, "w") as f:
        for ep_idx in range(total_episodes):
            row_out = {
                "episode_index": ep_idx,
                "stats": _to_serializable(per_ep_stats[ep_idx]),
            }
            f.write(json.dumps(row_out) + "\n")

    print(f"Wrote {episodes_stats_path}")

    # ── 9. Copy meta/stats.json ───────────────────────────────────────────────
    shutil.copy(SRC_ROOT / "meta" / "stats.json", DST_ROOT / "meta" / "stats.json")
    print("Copied stats.json")

    # ── 10. Write meta/info.json (v2.1 format) ────────────────────────────────
    dst_info = {
        "codebase_version": "v2.1",
        "robot_type": robot_type,
        "total_episodes": total_episodes,
        "total_frames": total_frames,
        "total_tasks": len(task_map),
        "total_videos": 0,
        "total_chunks": (total_episodes + CHUNKS_SIZE - 1) // CHUNKS_SIZE,
        "chunks_size": CHUNKS_SIZE,
        "fps": fps,
        "splits": {"train": f"0:{total_episodes}"},
        "data_path": "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet",
        "video_path": None,
        "features": features,
    }
    with open(DST_ROOT / "meta" / "info.json", "w") as f:
        json.dump(dst_info, f, indent=4)
    print(f"Wrote meta/info.json (codebase_version=v2.1)")

    print("\nDone! Dataset written to:")
    print(f"  {DST_ROOT}")
    print(f"  episodes: {total_episodes}, frames: {total_frames}")


if __name__ == "__main__":
    main()
